apiVersion: v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672        
        env:
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmq
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmq
      restartPolicy: Always
