services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    #command: azurite --skipApiVersionCheck
    volumes:
      -  ~/docker-volumes/azurite:/data
