apiVersion: v1
kind: Service
metadata:
  name: azurite
spec:
  type: NodePort
  ports:
  - name: "10000"
    port: 10000
    targetPort: 10000
    nodePort: 31000
    protocol: TCP
  - name: "10001"
    port: 10001
    targetPort: 10001
    nodePort: 31001
    protocol: TCP
  - name: "10002"
    port: 10002
    targetPort: 10002
    nodePort: 31002
    protocol: TCP
  selector:
    app: azurite
